# Generated by Django 2.1.4 on 2019-04-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=1500, verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, upload_to='article/', verbose_name='Изображение')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('moder', models.BooleanField(default=False, verbose_name='Модерация')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['create'],
            },
        ),
    ]
