# Generated by Django 2.1.4 on 2019-04-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, upload_to='post/', verbose_name='Изображение')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('moder', models.BooleanField(default=False, verbose_name='Модерация')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'post',
                'ordering': ['create'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
